/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/assistant.glb -o src/components/Avatar.jsx -r public 
*/

import React, { useEffect, useMemo, useRef } from 'react';
import { useFrame, useGraph } from '@react-three/fiber';
import { useAnimations, useFBX, useGLTF } from '@react-three/drei';
import { SkeletonUtils } from 'three-stdlib';
import generateLipSyncFromText from '../utils/lipsync';

const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};
export function Avatar({ animation, setAnimation, speakingText, ...props }) {
  const group = useRef();
  // Load the model GLB
  const { scene } = useGLTF('/models/assistant.glb');
  const clone = useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  // Load and name the animations
  const { animations: idleAnimation } = useFBX('/animation/Idle.fbx');
  const { animations: angryAnimation } = useFBX('/animation/Angry Gesture.fbx');
  const { animations: greetingAnimation } = useFBX('/animation/Standing Greeting.fbx');

  idleAnimation[0].name = "Idle";
  angryAnimation[0].name = "Angry";
  greetingAnimation[0].name = "Greeting";

  // Combine the animations
  const allAnimations = useMemo(() => [
    idleAnimation[0],
    angryAnimation[0],
    greetingAnimation[0],
  ], [idleAnimation, angryAnimation, greetingAnimation,]);
  // Get the animation actions
  // actions: return object of all animations (play, stop)
  const { actions } = useAnimations(allAnimations, group);

  // Play the animation based on the 'animation' prop
  useEffect(() => {
    // Stop all animations
    Object.values(actions).forEach(action => action.stop());

    // Play the current animation if it exists
    if (actions[animation]) {
      actions[animation].reset().fadeIn(0.5).play();
    }

    return () => {
      if (actions[animation]) {
        actions[animation].fadeOut(0.5);
      }
    };
  }, [animation, actions]);

  const head = nodes.Wolf3D_Head;
  const teeth = nodes.Wolf3D_Teeth;
  const visemeIndex = useMemo(() => {
    const idx = {};
    for (const key in corresponding) {
      const morphName = corresponding[key];
      idx[key] = head.morphTargetDictionary[morphName];
    }
    return idx;
  }, [head]);

  const lipSyncData = useMemo(() => generateLipSyncFromText(speakingText), [speakingText]);
  const startTime = useRef(0);

  useEffect(() => {
    if (speakingText) {
      startTime.current = performance.now();
    }
  }, [speakingText]);

  useFrame(() => {
    if (!speakingText) {
      nodes.Wolf3D_Head.morphTargetInfluences.fill(0);
      nodes.Wolf3D_Teeth.morphTargetInfluences.fill(0);
      return;
    }

    const t = (performance.now() - startTime.current) / 1000;
    const current = lipSyncData.findLast(e => e.time <= t);

    // Reset morph targets
    head.morphTargetInfluences.fill(0);
    teeth.morphTargetInfluences.fill(0);

    // Apply the morph target using the pre-calculated index
    if (current && current.mouth && visemeIndex[current.mouth] !== undefined) {
      const index = visemeIndex[current.mouth];
      head.morphTargetInfluences[index] = 1;
      teeth.morphTargetInfluences[index] = 1;
    }
  });

  return (
    <group {...props} dispose={null} ref={group}>
      <primitive object={nodes.Hips} />
      <skinnedMesh geometry={nodes.Wolf3D_Hair.geometry} material={materials.Wolf3D_Hair} skeleton={nodes.Wolf3D_Hair.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
      <skinnedMesh name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
      <skinnedMesh name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
      <skinnedMesh name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
    </group>
  );
}

useGLTF.preload('/models/assistant.glb');